---

antora:
  name: modules
  dir: www
  modules:
    - name: 01-ansible-navigator-intro
      label: Introduce the environment
      solveButton: true
    - name: 02-ansible-navigator-explore-ui
      label: Exploring the ansible-navigator interface
      solveButton: true
    - name: 03-configure-ansible-navigator
      label: Configuring common ansible-navigator options
      solveButton: true
    - name: 04-ansible-navigator-using-execution-environments
      label: Using execution environments
      solveButton: true
    - name: 05-navigator-quiz
      label: Knowledge check
      solveButton: true


tabs:
  - name: VSCode Editor
    port: 8443
    path: /?folder=/home/rhel/ansible-files/

  